### ISSUE TITLE
Wrong "nominal voltages" for the IEEE cases

### ISSUE THREAD

**Issue by BDonnot** [powsybl/pypowsybl#120]
* **Do you want to request a *feature* or report a *bug*?**

In my opinion this is a bug.

* **What is the current behavior?**

Today, when loading a IEEE test case, for example:
```python
import pyposybl as pypo
net = pypo.network.create_ieee118()
net.create_voltage_levels_data_frame()
```
Returns a dataframe with "nominal_voltage" always equal to 1.0:
```
      substation_id  nominal_v  high_voltage_limit  low_voltage_limit
id                                                                   
VL1             S14        1.0                 NaN                NaN
VL2             S19        1.0                 NaN                NaN
VL3             S17        1.0                 NaN                NaN
VL4             S23        1.0                 NaN                NaN
VL5             S21        1.0                 NaN                NaN
...             ...        ...                 ...                ...
VL114           S28        1.0                 NaN                NaN
VL115           S26        1.0                 NaN                NaN
VL116           S70        1.0                 NaN                NaN
VL117           S68        1.0                 NaN                NaN
VL118           S65        1.0                 NaN                NaN
```

For some IEEE, voltage levels are not specified, but for some others (including the 118) they are (see https://matpower.org/docs/ref/matpower5.0/case118.html ) where there are 3 voltage levels:
```
0460 mpc.bus_name = {
0461     'Riversde  V2';
0462     'Pokagon   V2';
0463     'HickryCk  V2';
0464     'NwCarlsl  V2';
0465     'Olive     V2';
0466     'Kankakee  V2';
0467     'JacksnRd  V2';
0468     'Olive     V1';
0469     'Bequine   V1';
0470     'Breed     V1';
etc. etc.
```

Usually, people take V1 = 138 kV, V2=161 kV and V3 = 345 kV 
In (py)powsybl it seems every voltage levels is V = 1.0 kV

The same surprising behaviour arise for the case14, where in matpower:
```
mpc.bus_name = {
0091     'Bus 1     HV';
0092     'Bus 2     HV';
0093     'Bus 3     HV';
0094     'Bus 4     HV';
0095     'Bus 5     HV';
0096     'Bus 6     LV';
0097     'Bus 7     ZV';
0098     'Bus 8     TV';
0099     'Bus 9     LV';
0100     'Bus 10    LV';
0101     'Bus 11    LV';
0102     'Bus 12    LV';
0103     'Bus 13    LV';
0104     'Bus 14    LV';
0105 };
```
(see https://matpower.org/docs/ref/matpower5.0/case14.html)
For this one there is no "conventional" value (as far as I know), but i would assume HV to be 135 kV, LV to be 20kV and ZV 14 kV and LV to be 12 kV (for example)

This bug implies that in the current (py)powsybl implementation, on these grids, there are transformers between the same voltage levels on both their side. I'm not sure this is a desired behavior.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

To reproduce it retrieve the voltage levels using pypowsybl:
```python
import pypowsybl as pypo
net_118 = pypo.creat_ieee118()
print(net_118.create_voltage_levels_data_frame())
net_14= pypo.creat_ieee14()
print(net_14.create_voltage_levels_data_frame())
```

* **What is the expected behavior?**

The expected behaviour is to have at least 3 different voltage levels for the case 118 and for the case 14, to have "more realistic" transformers operating on different voltage levels at both their side, which is not the case at the moment.

* **What is the motivation / use case for changing the behavior?**

See above.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

```
Powsybl versions:
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
| Repository name             | Maven project version | Git branch | Git version                              | Build timestamp               |
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
| powsybl-open-loadflow       | 0.11.0                | UNKNOWN    | eb1f53612a03c0468a6156de89aacc4012674443 | 2021-05-27T09:50:07.767+02:00 |
| powsybl-single-line-diagram | 2.2.0                 | UNKNOWN    | b97b2d54108bad50fd2a9c1050bc0423f2499e86 | 2021-05-26T22:08:52.780+02:00 |
| powsybl-core                | 4.2.0                 | UNKNOWN    | 929bbaf93ff7bfb6481d04824c21e81b8800764f | 2021-05-25T11:14:38.408+02:00 |
| powsybl-rte-core            | 3.2.0                 | UNKNOWN    | 76c88c56886fd55b82bf0e76c8a2efeda55a75ce | 2021-05-27T11:29:00.743+02:00 |
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
```

**Comment by geofjamg** [comment]
Thanks, I was not aware there is additional conventions based in bus id. I guess this is convention more related to matpower use of IEEE CDF than original IEEE CDF spec? 
We will add it to IEEE CDF and Matpower importers but that won't change calculation results as it is just a matter of having or not per united data in the model. Having same nominal level on both sides of a transformer is normal in case of a per united model.

**Comment by BDonnot** [comment]
Indeed, it will not change the p and q, but will change the amps (if computed somewhere).

In the original spec, they specified the transformers, so basically which part of the grid have different voltages, but indeed, all the values given are in pair unit, so independent from the actual voltage level.
This is why they did not bother to put actual voltage (in kV) in the original data.

**Comment by geofjamg** [comment]
What would you take for V4 like in the 57 buses?
https://matpower.org/docs/ref/matpower5.0/case57.html 
It seems that there is no base voltage associated to buses in the matpower case.

**Comment by BDonnot** [comment]
I never really used this grid, but the team from pandapower (Fraunhoffer https://github.com/e2nIEE/pandapower) used the voltages (in kV): 115, 138, 161, 230, 345 and 500

**Comment by geofjamg** [comment]
Fixed by https://github.com/powsybl/powsybl-core/pull/1765 in next release 0.9

**Comment by geofjamg** [comment]
I re-open this issue because fix on powsybl core #1765 seems to have introduced a bug. 
For instance, by adding the 4 nominal voltages HH, LV, TV ZV to the IEEE 14, some lines now have a different nominal voltage at both sides like for branch 7 - 8 with 14Kv at side 1 and 20 Kv for the other.

For a modelling point of view, we need in that case to add an ideal transfo of 20/14 (and we do it for a long time in hades2 for instance, for having a correct model dealing with many CGMES IGMs containing equivalent lines). But in the case of the IEEE 14, when adding this ideal transfo the calculated state is farther from the initial solved state than without (and it makes sense as calculation has probably been done using 1 Kv nominal voltages).

 So I am not sure anymore it was a good idea to add this nominal voltages or maybe theses inconsistent nominal voltages.

@BDonnot @annetill @sylvlecl what do you think about this?

**Comment by BDonnot** [comment]
I can provide you with (lots) of references input / ouput pairs for the case14 file if you want (with the voltages mentionned above)

There are 5 transformers in the case 14 grid:
- 4 to 7 (138 kV to 14 kV)
- 4 to 9 (138 kV to 20 kV)
- 5 to 6 (138 kV to 20 kV)
- 7 to 8 (14 kV to 12 kV)
- 9 to 7 (20 kV to 14 kV)

I'm not sure i fully understand the issue when adding these transformers in pypowsybl.

**Comment by geofjamg** [comment]
https://matpower.org/docs/ref/matpower5.0/case14.html
There is only 3 transformers here?

**Comment by geofjamg** [comment]
I'm just saying that if you consider the 5 transformers, you won't find same voltages magnitude and angle than ones from the files.

**Comment by BDonnot** [comment]
> https://matpower.org/docs/ref/matpower5.0/case14.html
There is only 3 transformers here?

No i'm not sure. I think in matpower, when you have a line with a resistance of 0. it's a trafo.

So i would say that:
```
0068     7    8    0    0.17615    0    0    0    0    0    0    1    -360    360;
0069     7    9    0    0.11001    0    0    0    0    0    0    1    -360    360;
```
are two transformers, with a tap ratio of 1.0. As you see it makes sense as they are not connected to the same voltage levels:

```
0097     'Bus 7     ZV';
0098     'Bus 8     TV';
0099     'Bus 9     LV';
```


The other three are:
```
0062     4    7    0    0.20912    0    0    0    0    0.978    0    1    -360    360;
0063     4    9    0    0.55618    0    0    0    0    0.969    0    1    -360    360;
0064     5    6    0    0.25202    0    0    0    0    0.932    0    1    -360    360;
```
with tap ratio different from 1.


Also, note from here:
http://labs.ece.uw.edu/pstca/pf14/pg_tca14fig.htm

That the "extra two" transformers are in fact a "three winding transformers" connecting 4, 8 and 9 and that, to model it in the original CDF format, they introduce a "fake" bus (bus 7) that connects the three part of this transformer:
- 4 - 7
- 7 - 8
- 7 - 9

And they decided that the ratio of this 3 windings trafo was put on the "branch" 4-7.

Maybe there is a more suited way to model that in powsybl.

**Comment by BDonnot** [comment]
I just checked with the "pandapower" powerflow (simple powerflow without heursitic for qmin / qmax and in "single slack" mode) and the results of the original file can be retrieved:

```python
import pandapower as pp
import pandapower.networks as pn
net = pn.case14() 
pp.runpp(net)
net.res_bus 
```

prints:
```
>>> net.res_bus   
       vm_pu  va_degree        
0   1.060000   0.000000
1   1.045000  -4.982589
2   1.010000 -12.725100
3   1.017671 -10.312901
4   1.019514  -8.773854
5   1.070000 -14.220946 
6   1.061520 -13.359627
8   1.055932 -14.938521
9   1.050985 -15.097288
10  1.056907 -14.790622
11  1.055189 -15.075585
12  1.050382 -15.156276
13  1.035530 -16.033645
```

On the orignal matpower file results are:

```
          bus_i      Vm        Va
0026     1        1.06         0     
0027     2        1.045       -4.98     
0028     3        1.01       -12.72    
0029     4        1.019      -10.33    
0030     5        1.02        -8.78    
0031     6        1.07       -14.22   
0032     7        1.062      -13.37   
0033     8        1.09       -13.36 
0034     9        1.056      -14.94 
0035     10       1.051      -15.1 
0036     11       1.057      -14.79  
0037     12       1.055      -15.07 
0038     13       1.05       -15.16 
0039     14       1.036      -16.04 
```

They look pretty close (up to 0.1 degree / kV i believe)

**Comment by EtienneLt** [comment]
I think it is fixed
