### ISSUE TITLE
Wrong sign convention in the generators dataframe

### ISSUE THREAD

**Issue by BDonnot** [powsybl/pypowsybl#121]
* **Do you want to request a *feature* or report a *bug*?**
This is, in my opinion, a bug.

* **What is the current behavior?**
In the generators dataframe, after a powerflow has been run, there is an inconsistency between the "input" of the powerflow (that are `target_p`, `max_p`, `min_p` and `target_q`) and the output of the powerflow (that are `p` and `q`)

Indeed, in the "input" columns, generators adopt the "*generator convention*" (so positive power means power is injected to the node at which the unit is connected) whereas for the results it seems that the "*load convention*" is used (positive power means some power is "taken" from the node to the unit).

This has some weird effects:
- `p` and `target_p` are often of opposite sign
- `p` is way below `min_p` , because the sign is inverted

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
To reproduce it, computes the generators data frame after having run an ac powerflow:

```python
import pypowsybl as pypo
net = pypo.network.create_ieee14()
pypo.loadflow.run_ac(net)
net.create_generators_data_frame()
```

It prints:

```
     energy_source  target_p   max_p   min_p  target_v  target_q  voltage_regulator_on      p          q voltage_level_id bus_id
id                                                                                                                              
B1-G         OTHER     232.4  9999.0 -9999.0     1.060     -16.9                  True -232.4  16.550203              VL1  VL1_0
B2-G         OTHER      40.0  9999.0 -9999.0     1.045      42.4                  True  -40.0 -43.559051              VL2  VL2_0
B3-G         OTHER       0.0  9999.0 -9999.0     1.010      23.4                  True   -0.0 -25.075897              VL3  VL3_0
B6-G         OTHER       0.0  9999.0 -9999.0     1.070      12.2                  True   -0.0 -12.731397              VL6  VL6_0
B8-G         OTHER       0.0  9999.0 -9999.0     1.090      17.4                  True   -0.0 -17.623750              VL8  VL8_0

```
And as you can see, for all lines, the `p` columns is negative (`-232.4` and `-40.0`) whereas the `target_p` column is positive (`232.4`, `40.0`)

* **What is the expected behavior?**
In the above case, all "input" and "output" columns should have the same sign for consistency: assign either the "generator convention" to generator, or the "load convention" to them. (of course "generator convention" would be better in this case)

In my opinion it is error prone to change the convention between the "input" and "output"

* **What is the motivation / use case for changing the behavior?**

See above

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: Ubuntu 20.04

```
Powsybl versions:
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
| Repository name             | Maven project version | Git branch | Git version                              | Build timestamp               |
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
| powsybl-open-loadflow       | 0.11.0                | UNKNOWN    | eb1f53612a03c0468a6156de89aacc4012674443 | 2021-05-27T09:50:07.767+02:00 |
| powsybl-single-line-diagram | 2.2.0                 | UNKNOWN    | b97b2d54108bad50fd2a9c1050bc0423f2499e86 | 2021-05-26T22:08:52.780+02:00 |
| powsybl-core                | 4.2.0                 | UNKNOWN    | 929bbaf93ff7bfb6481d04824c21e81b8800764f | 2021-05-25T11:14:38.408+02:00 |
| powsybl-rte-core            | 3.2.0                 | UNKNOWN    | 76c88c56886fd55b82bf0e76c8a2efeda55a75ce | 2021-05-27T11:29:00.743+02:00 |
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
```

**Comment by geofjamg** [comment]
Hi,

This is not really a bug, as it is IIDM convention. Convention is not the same for inputs and outputs. For outputs everything is in load convention to easy bus balance calculation by just summing values.
This is very similar to the convention used in CGMES.

**Comment by BDonnot** [comment]
Ok this sounds weird, but why not.

It makes it easier to check kirchhoff laws, but it's a bit weird to have a resulting `p` lower than `p_min`. But there is no perfect solution for this problem, so i imagine that's fine :-)

If that's intentional, i'm gonna write a bit of doc in the python wrapper to make sure it's written somewhere and avoid any confusing.
