### ISSUE TITLE
Integration with python logging API

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#142]
* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

Java logging configuration is "hardcoded" in a logback config file, the only thing the user can do is setting the log level to `DEBUG` by calling the method `pypowsybl.set_debug_mode`.

* **What is the expected behavior?**

We could try to integrate java logs to python logging framework.
In order to achieve this, a solution would be to implement SLF4J API so that loggers actually send logs to python loggers.

_**As of now, it's not clear if it's worth the effort**_

* **What is the motivation / use case for changing the behavior?**

Giving the hand to python user on powsybl logs, using its usual logging API.

**Comment by geofjamg** [comment]
Design proposition:
 - On Java side, use logback-classic to store logs with a new appender:
Example:
```java
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.AppenderBase;
import org.slf4j.LoggerFactory;
import ch.qos.logback.classic.Logger;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class LoggerTest {

    private static final Logger LOGGER = (Logger) LoggerFactory.getLogger(LoggerTest.class);

    public static class ListAppender<E> extends AppenderBase<E> {

        private final List<E> list = new ArrayList<>();

        protected synchronized void append(E e) {
            list.add(e);
        }

        public synchronized List<E> getListAndClear() {
            List<E> listCopy = new ArrayList<>(list);
            list.clear();
            return listCopy;
        }
    }

    public static void main(String[] args) {
        // create and start a ListAppender
        ListAppender<ILoggingEvent> listAppender = new ListAppender<>();
        listAppender.start();

        // add the appender to the logger
        LOGGER.addAppender(listAppender);

        LOGGER.info("toto {}", 1);
        LOGGER.info("tutu {}", "sss");

        // JUnit assertions
        List<ILoggingEvent> logsList = listAppender.getListAndClear();
        System.out.println(logsList.get(0).getMessage());
        System.out.println(logsList.get(0).getFormattedMessage());
        System.out.println(logsList.get(0).getLevel());
        System.out.println(Arrays.toString(logsList.get(0).getArgumentArray()));
        System.out.println(logsList.get(0).getLoggerName());
        System.out.println(logsList.get(0).getTimeStamp());
   }
}
```
  - In the `Util.doCatch`, fill `PyPowsyblApiHeader.ExceptionHandlerPointer` with new logs (so create a struct modelling logs, on C side) => Maybe rename ExceptionHandlerPointer to something that is more generic as it will not carry anymore only exception message but all new logs.
  - On C++ side after each Java call, get logs, fill Python Logger with no logs (A Python objet can be easily accessed on C++ side using pybind11) https://docs.python.org/3/library/logging.html
    - Log level theshold on Python API has to be taken into account to only transfer logs with corresponding level.
    
Remarks: logs will be displayed on Python side by bulk after each Java call (but maybe not really a bug issue?)

Questions:
  - How to map logger name from Java to Python? Maybe not an issue as it is string in Java and Python but in Java it represents fully qualified classes and in Python it represents generally modules.
  - Same for log levels? 
In Java, trace, debug, info, warn, error. In Python debug, info, warning, error, critical + custom
    - trace -> custom trace
    - debug -> debug
    - info -> info
    - warning -> warning
    - error -> error

**Comment by obrix** [comment]
@geofjamg  After our discussion there is two design possibilities to investigate :

* Using callbacks from java to C++ to bring back the logs instead of relying on the "doCatch exception" mechanism described above. This would be a more direct way to log from java, avoiding the issue of bringing back logs as group.

* Finding a way to propagate the changes on python logger (log level...) to java logger "automatically" to filter directly from java. This can be done by forcing a synchronization of logging informations each time a java call is made from C++.

I will investigate the feasibility of those two points first.
