### ISSUE TITLE
[Security analysis] Return violations as a dataframe

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#143]
* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

Violations are reported in a tree of python objects, themselves mapped on C structures.

* **What is the expected behavior?**

It will be simpler and more consistent with other parts of the python API to return them as a pandas dataframe.

The dataframe index needs to contain the contingency ID (empty string for pre-contingency violations).
To be confirmed: should we make it a multi-indexed dataframe, with for example information about the subject of the violation for other columns ? Not sure it has an added value for now.

* **What is the motivation / use case for changing the behavior?**

* From the implementation point of view, simplify the mapping of limit violation results from java to python
* From the user point of view, having a more consistent API, largely based on pandas dataframes

**Comment by geofjamg** [comment]
Maybe the violation type as a second index? We often need to get for instance only current violation.

**Comment by EtienneLt** [comment]
> Maybe the violation type as a second index? We often need to get for instance only current violation.

will a triple index with violation id contingency id and violation type do the job ?

**Comment by sylvlecl** [comment]
Why not but we must keep the contingency ID first to have a tree-like structure.

The "issue" is that in any case, even a tuple (`contingency_id`, `violation_type`, `subject_id`) will not be unique : for example you can have violations on sides 1 and 2 of a line, or on multiple buses in a voltage level.

I am not enough used to using pandas to estimate if it has an added value to add `subject_id` to the index columns, instead of having it in a "normal" column. 
Actually you can also filter on normal columns, so the added value is not clear to me. Maybe when selecting on an index columns we have better performance?

If anyone knows ... :)

**Comment by sylvlecl** [comment]
Implemented in #145
