### ISSUE TITLE
update current limits

### ISSUE THREAD

**Issue by EtienneLt** [powsybl/pypowsybl#167]
* **Do you want to request a *feature* or report a *bug*?**

feature

* **What is the current behavior?**

Current limits can't be modified on a network 

* **What is the expected behavior?**

allow the user to update current limit if he wish. An idea would be to get all the existing current limits on a side of a branch
as a dataframe. then the user can modify it and then the changes override the previous current limits. 

* **What is the motivation / use case for changing the behavior?**

allow to work with chosen current limits.

**Comment by sylvlecl** [comment]
#225 will be a prerequisite of that one

**Comment by EtienneLt** [comment]
solved with #341
