### ISSUE TITLE
Wrong limit value in voltage violation ?

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#175]
* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Violation seen in a security analysis result on eurostag example1 :
type = LOW_VOLTAGE
limit = 500.0 
value = 398.917401  

Their seem to be an inconsistency between those 3 values: maybe the limit is wrong ?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```python
network = pn.create_eurostag_tutorial_example1_network()
network.update_loads(pd.DataFrame(columns=['p0'], data=[800], index=['LOAD']))
analysis = ps.create_analysis()
res = analysis.run_ac(network)
res.limit_violations
```

* **What is the expected behavior?**

If the violation is a "low voltage" violation, we should have a value LOWER than the limit, not higher.

**Comment by yichen88** [comment]
it would be fixed in PR of OLF => https://github.com/powsybl/powsybl-open-loadflow/pull/328

**Comment by sylvlecl** [comment]
Closing, will be fixed with next release of OLF, thank you!
