### ISSUE TITLE
Expose export parameters

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#178]
* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

The list of import parameters is available, but not the list of export parameters.

* **What is the expected behavior?**

The list of export parameters should be available as well.
It will require the implementation of https://github.com/powsybl/powsybl-core/issues/1785 first.

* **What is the motivation / use case for changing the behavior?**

In particular, being able to know what property to use to select the XIIDM version.

**Comment by geofjamg** [comment]
Solved by #182
