### ISSUE TITLE
Java stack trace in debug mode

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#185]
* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

When an exception occurs on java side, we don't always have enough information to understand the error.
(in particular, when we have nothing in the message, or the message is not rich enough)

* **What is the expected behavior?**

It would be very useful to be able to retrieve the full stack trace of an exception, when in debug mode.

* **What is the motivation / use case for changing the behavior?**

Maintainability.

**Comment by geofjamg** [comment]
The Java stack trace is accessible using the 
```python 
pypowsybl.set_debug_mode(True)
```
And #142 will improve error access to users.
