### ISSUE TITLE
Clean up public API

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#210]
* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

_(See comments below, the goal of the issue has slightly changed, but I leave the initial goal here in order not make the discussion senseless)_

Features are only accessible by importing their implementation from inner modules, for example `pypowsybl.network`, `pypowsybl.loadflow`.

* **What is the expected behavior?**

It seems recommended in python (cannot find the reference anymore, will update) to have as much as possible the API in one root package. Indeed, when you used libs such as `numpy` or `pandas` you more or less never need to import submodules.

We could try to follow the same path by importing all widely used classes/methods in `pypowsybl/__init__.py`.

This is open to discussion.

* **What is the motivation / use case for changing the behavior?**

Ease of use / conformance to the language best practices.

For example it would avoid to import multiple modules when you only want to read a file and run a loadflow.

**Comment by geofjamg** [comment]
If you look at some other successful libraries like tensorflow and pytorch there is many subpackages that are use as a namespace like in pypowsybl (this has been my reference design)

**Comment by sylvlecl** [comment]
Yes, the issue is really to discuss pros/cons, it may not be a good fit for pypowsybl.

In numpy and pandas everything is centered around 1 object basically (array and dataframe), so it makes sense to have one main module. When you have multiple very distinct features (like loadflow and dynamic simulation), it may not be that meaningful.

**Comment by sylvlecl** [comment]
But, in any case, the important point is that we should be more careful than we are today about what we expose in our "public" modules, be it only the root package or other modules.

For example, today in `pypowsybl/network.py` we have those imports:
```python
import _pypowsybl
import sys
from _pypowsybl import ElementType
from _pypowsybl import PyPowsyblError
from typing import List
from typing import Set

import pandas as pd
import datetime

from pypowsybl.util import create_data_frame_from_series_array
```
It means that `sys`, `List`, `Set`, `pd` and `datetime` are exposed in the public API of `pypowsybl.network` module. It means that your IDE will propose autocompletion for them, for instance. We should really remove all those artifacts !

Even in libs like tensorflow with submodules, each module is carefully populated with only the relevant names. It's achieved with a combination of `_` prefixed names, of methods and classes selectively imported from internal modules, etc.

**Comment by sylvlecl** [comment]
I close that issue following #217, but it's something we need to keep in mind on the long run.

Maybe at some point we'll need to separate "internal" modules and public modules, like what's done in larger libs.
