### ISSUE TITLE
Network elements removal

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#338]
* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the expected behavior?**

We should be able to remove elements of the network.

* **What is the motivation / use case for changing the behavior?**

We can now create elements, but not remove them, which still does not allow all kinds of network modifications.

**Implementation** 

For single-indexed elements, the API would be straight forward:
```python
network.remove_generators(id=['GEN12', 'GEN56'])
```
Note that those methods must still be as flexible as possible, as other methods, accepting any array-like or dataframe as input.

For multi-indexed elements, it's less obvious. This includes:
 - current limits
 - ratio tap changer steps
 - phase tap changer steps
 - non linear shunt compensator sections
 - reactive capability curve points

Do we want to support the removal of only one of those objects ?

For now, creation is not supported for those kinds of elements, so I propose to not handle them at all,
in a first evolution.
If he really needs to modify those elements, the use will have to re-crate the "containing" element, for
example the transformer, for transformers steps.

**Comment by EtienneLt** [comment]
solved with #347
