### ISSUE TITLE
Looking for an example to create a system from scratch

### ISSUE THREAD

**Issue by cuihantao** [powsybl/pypowsybl#342]
* **Do you want to request a *feature* or report a *bug*?**
Feature request (an example) 

* **What is the current behavior?**
I'm looking to load a power system test case from [ANDES](https://github.com/cuihantao/andes) to pypowsybl. Currently, there is no tutorial on creating a power system from scratch. I looked at the API; it appears that I should call `create_` functions on an empty system, but I'm not sure about the correct sequence. 

Using version 0.13.0, I tried the following, and it throws an error:

```python
new = pp.network.create_empty()
new.create_buses(id=["1"], name=["Bus_1"], voltage_level_id = ["VL1"])
```

```
---------------------------------------------------------------------------
PyPowsyblError                            Traceback (most recent call last)
Input In [80], in <cell line: 1>()
----> 1 new.create_buses(id=["1"], name=["Bus_1"], voltage_level_id = ["VL1"])

File ~/mambaforge/envs/a/lib/python3.9/site-packages/pypowsybl/network.py:2578, in Network.create_buses(self, df, **kwargs)
   2562 def create_buses(self, df: _DataFrame = None, **kwargs: _ArrayLike) -> None:
   2563     """
   2564     Creates buses.
   2565 
   (...)
   2576         **kwargs: Attributes as keyword arguments.
   2577     """
-> 2578     return self._create_elements(ElementType.BUS, [df], **kwargs)

File ~/mambaforge/envs/a/lib/python3.9/site-packages/pypowsybl/network.py:2492, in Network._create_elements(self, element_type, dfs, **kwargs)
   2490     else:
   2491         c_dfs.append(_create_c_dataframe(df, metadata[i]))
-> 2492 _pp.create_element(self._handle, c_dfs, element_type)

PyPowsyblError: 
```
The error output is not very informative. Also tried passing a dataframe with these fields, but got

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [83], in <cell line: 1>()
----> 1 new.create_buses(df)

File ~/mambaforge/envs/a/lib/python3.9/site-packages/pypowsybl/network.py:2578, in Network.create_buses(self, df, **kwargs)
   2562 def create_buses(self, df: _DataFrame = None, **kwargs: _ArrayLike) -> None:
   2563     """
   2564     Creates buses.
   2565 
   (...)
   2576         **kwargs: Attributes as keyword arguments.
   2577     """
-> 2578     return self._create_elements(ElementType.BUS, [df], **kwargs)

File ~/mambaforge/envs/a/lib/python3.9/site-packages/pypowsybl/network.py:2491, in Network._create_elements(self, element_type, dfs, **kwargs)
   2489         c_dfs.append(None)
   2490     else:
-> 2491         c_dfs.append(_create_c_dataframe(df, metadata[i]))
   2492 _pp.create_element(self._handle, c_dfs, element_type)

File ~/mambaforge/envs/a/lib/python3.9/site-packages/pypowsybl/utils/dataframes.py:102, in _create_c_dataframe(df, series_metadata)
    100     columns_values.append(series.values)
    101     is_index.append(False)
--> 102 return _pp.create_dataframe(columns_values, columns_names, columns_types, is_index)

RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

I wonder if you can put up an example for creating a case from scratch? It doesn't have to be complex; just a three-bus system with three lines, one load, two generators (slack and PV), and a shunt compensator.

* **What is the motivation / use case for changing the behavior?**

I'm looking to make ANDES interoperable with pypowsybl, which I believe has a huge potential. 

* **Please tell us about your environment:**
  - PowSyBl Version: 0.13.0
  - OS Version: Debian testing with 5.15.0-3-amd64

**Comment by EtienneLt** [comment]
Hello 
Thank you for your comment, we will add more documentation
You need to first create the stations and the voltagelevel then the buses 
a full example to create a network from scratch is :
```python
n = pn.create_empty()
stations = pd.DataFrame.from_records(index='id', data=[
    {'id': 'S1', 'country': 'BE'},
    {'id': 'S2', 'country': 'DE'}
])
n.create_substations(stations)

voltage_levels = pd.DataFrame.from_records(index='id', data=[
    {'substation_id': 'S1', 'id': 'VL1', 'topology_kind': 'BUS_BREAKER', 'nominal_v': 400},
    {'substation_id': 'S2', 'id': 'VL2', 'topology_kind': 'BUS_BREAKER', 'nominal_v': 400},
])
n.create_voltage_levels(voltage_levels)

buses = pd.DataFrame.from_records(index='id', data=[
    {'voltage_level_id': 'VL1', 'id': 'B1'},
    {'voltage_level_id': 'VL2', 'id': 'B2'},
])
n.create_buses(buses)

lines = pd.DataFrame.from_records(index='id', data=[
    {'id': 'LINE', 'voltage_level1_id': 'VL1', 'voltage_level2_id': 'VL2', 'bus1_id': 'B1', 'bus2_id': 'B2',
     'r': 0.1, 'x': 1.0, 'g1': 0, 'b1': 1e-6, 'g2': 0, 'b2': 1e-6}
])
n.create_lines(lines)

loads = pd.DataFrame.from_records(index='id', data=[
    {'voltage_level_id': 'VL2', 'id': 'LOAD', 'bus_id': 'B2', 'p0': 100, 'q0': 10}
])
n.create_loads(loads)

generators = pd.DataFrame.from_records(index='id', data=[
    {'voltage_level_id': 'VL1', 'id': 'GEN', 'bus_id': 'B1', 'target_p': 100, 'min_p': 0, 'max_p': 200,
     'target_v': 400, 'voltage_regulator_on': True}
])
n.create_generators(generators)
```

**Comment by EtienneLt** [comment]
and to create a shunt compensator
```python
shunt_df = pd.DataFrame.from_records(
        index='id',
        columns=['id', 'name', 'model_type', 'section_count', 'target_v',
                 'target_deadband', 'voltage_level_id', 'node'],
        data=[('SHUNT1', '', 'NON_LINEAR', 1, 400, 2, 'S1VL2', 2),
              ('SHUNT2', '', 'NON_LINEAR', 1, 400, 2, 'S1VL2', 10)])
model_df = pd.DataFrame.from_records(
        index='id',
        columns=['id', 'g', 'b'],
        data=[('SHUNT1', 1, 2),
              ('SHUNT1', 3, 4),
              ('SHUNT2', 5, 6),
              ('SHUNT2', 7, 8)])
n.create_shunt_compensators(shunt_df, non_linear_model_df=model_df)
```

**Comment by cuihantao** [comment]
Thank you for the reply! The example code looks good! Let me try it later today.

**Comment by cuihantao** [comment]
Hi @EtienneLt ,

It looks like the underlying library is strict about the data type. When creating substations, if `id`s are integers, RutimeError will be thrown:

```
n = pp.network.create_empty()

stations = pd.DataFrame.from_records(index='id', data=[
    {'id': 1, 'country': 'BE'},
    {'id': 2, 'country': 'DE'}
])
n.create_substations(stations)
```
It would be helpful to show a type error so that it can be identified more easily. Thank you.

**Comment by cuihantao** [comment]
The example code is very helpful. I managed to write a converter from ANDES to PyPowSybl and to save the single-line diagram. The issue is resolved for me.

On a side note, could you provide an argument for adjusting the zoom level of the network area diagram? It appears quite small for systems of a hundred buses.

**Comment by EtienneLt** [comment]
Hello,
Thank you for your comments, we will try to take them into account. 
Zoom level is planed but I don't think it will come so soon. It needs an evolution on module powsybl-network-area-diagram (https://github.com/powsybl/powsybl-network-area-diagram#powsybl-network-area-diagram)

**Comment by geofjamg** [comment]
Hi,

I don't know if it can solve you zoom issue, but it is possible to specify a subpart of the network for generating the diagram:
```python
network = pp.network.create_ieee14()
network.write_network_area_diagram_svg('ieee14.svg', 'VL4', 1)
```

**Comment by sylvlecl** [comment]
We have added some documentation about network elements, in the latest version of the doc:

- In the [user guides](https://pypowsybl.readthedocs.io/en/latest/user_guide/network.html#creating-network-elements)
- In the API reference, each create method now has some basic example, see for example [here](https://pypowsybl.readthedocs.io/en/latest/reference/api/pypowsybl.network.Network.create_buses.html#pypowsybl.network.Network.create_buses) for buses

I will close this issue since it has been considered resolved thanks to the provided examples :) 

The improvement of error messages will be handled in issue #356 .
