### ISSUE TITLE
bus_breaker_connectable_bus1_id and bus_breaker_connectable_bus2_id

### ISSUE THREAD

**Issue by geofjamg** [powsybl/pypowsybl#387]
* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
bus_breaker_bus1_id and bus_breaker_bus2_id are convenient to get original buses ID when coming from a bus/breaker topo (like a UCTE file). But when a line is disconnected, these attributes are None (which is fine).

* **What is the expected behavior?**
We could also have 2 additional attributes that represents the connectable bus of IIDM like bus_breaker_connectable_bus1_id and bus_breaker_connectable_bus2_id.

An alternative is to always have a value for bus_breaker_bus1_id and bus_breaker_bus2_id and an additional boolean for connection status (like in Java).

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by AnkurArohi** [comment]
@geofjamg  I think you meant 2_id if not I apologize

**Comment by geofjamg** [comment]
@sylvlecl what would you choose? the proposed solution or the alternative?

**Comment by sylvlecl** [comment]
Indeed it may be more understandable to put the connectable bus into the existing `bus_breaker_bus_id` attribute.

It should be enough, together with the existing `connected` attributes, unless I am missing something.

**Comment by CBiasuzzi** [comment]
forgive the naive question: the context here is "lines", but this feature should cover also the other equipments, right?
(equipments that have the attributes bus_breaker_bus_id and connected)

**Comment by geofjamg** [comment]
> forgive the naive question: the context here is "lines", but this feature should cover also the other equipments, right? (equipments that have the attributes bus_breaker_bus_id and connected)

Yes all connectable equipments
