### ISSUE TITLE
bug with get_bus_voltages_sensitivity_matrix()

### ISSUE THREAD

**Issue by EtienneLt** [powsybl/pypowsybl#392]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**

there is a NPE when getting the bus voltage sensibility matrix with a sensibility of the flow of the lines regarding generator active power

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```python
import pypowsybl as pp
network = pp.network.create_eurostag_tutorial_example1_network()
analysis = pp.sensitivity.create_ac_analysis()
analysis.set_branch_flow_factor_matrix(network.get_lines().index.to_list(),
                                           network.get_generators().index.to_list())
result = analysis.run(network)
result.get_bus_voltages_sensitivity_matrix()
```

**Comment by sylvlecl** [comment]
We now raise an exception with an explicit message, in that case, and for branch matrices which do not exist.
