### ISSUE TITLE
Slack terminal support

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#403]
* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

The slack terminal extension is not exposed.

* **What is the expected behavior?**

We should be able to manipulate that extension.
For example, the dataframe could look like:
```python
>>> network.get_extensions('slackTerminal')
       slack_element_id
id
'VL-1'           'BBS-1'
```

For the creation, we may support only a limited set of input types:
- bus bar sections for node breaker topologies
- buses for bus breaker topologies

* **What is the motivation / use case for changing the behavior?**

Being able to explicitly define the slack terminal.

**Comment by EtienneLt** [comment]
done
