### ISSUE TITLE
Import/export parameters: add possible values

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#406]
* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

We can get the list and a description of import/export parameter, but not the possible values, for parameters such as enums.

* **What is the expected behavior?**

In next powsybl-core release (4.9), the values of parameters will be available:
we should provide it in the parameters table.

**Comment by EtienneLt** [comment]
duplicate with https://github.com/powsybl/pypowsybl/issues/517
