### ISSUE TITLE
[CI] Separate partial PR builds and full, nightly builds

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#443]
* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

The CI is run, for every pull requests, on the whole OS x python matrix, which means currently 3 x 4 jobs.
We would like to support, in addition, windows 32 bits, and soon python 3.11, which would make 4 x 5 = 20 jobs.
That approach does not scale very well.

* **What is the expected behavior?**

The proposed approach is to separate:
- PR workflow, which will run on only 1 python version (3.8 for example), and for 3 OS (linux/mac/win)
- Nightly workflow, which will run once a day, with the full OS/python matrix.

The release workflow must, of course, also run on the full matrix.

* **What is the motivation / use case for changing the behavior?**

Providing the lib for more platforms, while keeping the CI jobs reasonably short.

**Comment by sylvlecl** [comment]
More thoughts and digging about this:

- maybe instead of the nightly build, we could run the full build only on main branch
- we can externalize the build logic into github actions in order to make it re-usable from different workflows

**Comment by AnkurArohi** [comment]
> More thoughts and digging about this:
> 
> - maybe instead of the nightly build, we could run the full build only on main branch
> - we can externalize the build logic into github actions in order to make it re-usable from different workflows

Full build only on Main branch is Standard practice
