### ISSUE TITLE
Equivalent Branches not modelled correctly in pypowsybl

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/pypowsybl#457]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

- pypowsybl and powsybl (guess) also is modelling Equivalent Branch Tag of CGMES to lines where as it should be actually modelled as series impedance.

- The advantage is that the impedance can possibly have slightly different voltages at its ends and also from a modelling perspective it is not a correct representation of the CGMES profile/ Network Data Model. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

pypowsybl after loading the zipped CGMES Network

* **What is the expected behavior?**

All Equivalent Branches should be modelled as a new df in Network with name
impedance

* **What is the motivation / use case for changing the behavior?**

- Close to real world/CGMES/DM modelling.

- Not included in line losses results, N-1 Line contingency case etc

- powsybl/IIDM in the background will not ignore/add a virtual trafo if these have different voltage levels on its terminals

* **Please tell us about your environment:**
  - PowSyBl Version: ... 0.17.0.dev1
  - OS Version: ...Fedora

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
IIDM lines support a different nominal voltage at its ends and a transfo is automatically created by simulators in that case.
Equivalent lines in IIDM should normally also be tagged as "fictitious" to distinguish them from normal lines.

**Comment by AnkurArohi** [comment]
> IIDM lines support a different nominal voltage at its ends and a transfo is automatically created by simulators in that case. Equivalent lines in IIDM should normally also be tagged as "fictitious" to distinguish them from normal lines.

yes but if i check the pypowsybl dataframe for get_lines() i do not see  "fictitious"

**Comment by geofjamg** [comment]
You are right, fictitious attribute is missing in all data frames.
We will add it for next release.

**Comment by sylvlecl** [comment]
Is #465 enough to solve this issue ?

**Comment by AnkurArohi** [comment]
Yes
