### ISSUE TITLE
Missing Buses after CGMES Import

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/pypowsybl#458]
* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

- It has been analysed that pypowsybl is missing buses which are actually modelled in SCADA and also is being modelled from the same CGMES in pandapower

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

- pandapower is importing the same CGMES and the network has 
 This pandapower network includes the following parameter tables:
   - bus (3165 elements)

Surprisingly pypowsybl as well as Powsybl has only 
powsybl_net.get_buses().shape
Out[64]: (89, 6)

89 buses.

* **What is the expected behavior?**

- There has to be a detailed analysis for the missing buses.
- I think (Guess) pypowsybl as well as powsybl is ignoring those buses whose SV files have v=0.0 and v_angle=0.0, but this should not be the case as they still need to be modelled for further topological/switch status changes

* **What is the motivation / use case for changing the behavior?**

- To be able to fully support the network model and include all the elements / Connectivity Nodes which are present in CGMES profile.

* **Please tell us about your environment:**
  - PowSyBl Version: ... 0.17.0.dev1
  - OS Version: ... Fedora

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
Is it a node/breaker model? 
"I think (Guess) pypowsybl as well as powsybl is ignoring those buses whose SV files have v=0.0 and v_angle=0.0," => SV does not impact what is imported or not. It is an optional input.
Could you try to provide a small test case that shows the issue? With just what a description we cannot do/analyse anything.

**Comment by AnkurArohi** [comment]
> Is it a node/breaker model? "I think (Guess) pypowsybl as well as powsybl is ignoring those buses whose SV files have v=0.0 and v_angle=0.0," => SV does not impact what is imported or not. It is an optional input. Could you try to provide a small test case that shows the issue? With just what a description we cannot do/analyse anything.

yes sure
I am thinking of an example

**Comment by AnkurArohi** [comment]
bus branch
I found why ?
powsybl/pypowsybl takes voltage level as bus where as CN should be

**Comment by geofjamg** [comment]
> bus branch
> I found why ?
> powsybl/pypowsybl takes voltage level as bus where as CN should be

No

**Comment by AnkurArohi** [comment]
It is node breaker

**Comment by AnkurArohi** [comment]
I will close this case, I think it is clear
