### ISSUE TITLE
Expose "fictitious" attribute of network elements

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#465]
* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

The "fictitious" attribute is available in java but not in pypowsybl.

* **What is the expected behavior?**

The attribute should be available as an optional attribute in all dataframes of network elements that support it in the IIDM model.

* **What is the motivation / use case for changing the behavior?**

In particular, distinguishing fictious lines from others, see #457

**Comment by AnkurArohi** [comment]
@sylvlecl 
There is already an open issue for this

**Comment by AnkurArohi** [comment]
https://github.com/powsybl/pypowsybl/issues/457
