### ISSUE TITLE
not able to install pypowsybl python package in Apple M1 chip

### ISSUE THREAD

**Issue by LZhangCognite** [powsybl/pypowsybl#486]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
can not install pypowsybl python package in my Mac M1 chip. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
I have tried pip, conda, poetry to install, nothing was able to install the package. 

* **What is the expected behavior?**
should install properly

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: N/A
  - OS Version: 12.4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
**When I use "pip install pypowsybl", I got this error message.** 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pypowsybl

**When I try to install with "conda install -c conda-forge pypowsybl", it gives me this error. ** 
PackagesNotFoundError: The following packages are not available from current channels:

  - pypowsybl

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

(if a question doesn't apply, you can delete it)

**Comment by AnkurArohi** [comment]
You need Graalvm , maven and you need to follow instructions on the installation page of pypowsybl

**Comment by AnkurArohi** [comment]
https://zzun.app/repo/powsybl-pypowsybl

**Comment by EtienneLt** [comment]
> You need Graalvm , maven and you need to follow instructions on the installation page of pypowsybl

That is to compile the project but to install normally you don't need to

**Comment by EtienneLt** [comment]
> * **Do you want to request a _feature_ or report a _bug_?**
>       bug
> 
>     * **What is the current behavior?**
>       can not install pypowsybl python package in my Mac M1 chip.
> 
>     * **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
>       I have tried pip, conda, poetry to install, nothing was able to install the package.
> 
>     * **What is the expected behavior?**
>       should install properly
> 
>     * **What is the motivation / use case for changing the behavior?**
> 
>     * **Please tell us about your environment:**
>       
>       * PowSyBl Version: N/A
>       * OS Version: 12.4
> 
>     * **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
>       **When I use "pip install pypowsybl", I got this error message.**
>       note: This error originates from a subprocess, and is likely not a problem with pip.
>       error: legacy-install-failure
> 
> 
> × Encountered error while trying to install package. ╰─> pypowsybl
> 
> **When I try to install with "conda install -c conda-forge pypowsybl", it gives me this error. ** PackagesNotFoundError: The following packages are not available from current channels:
> 
>     * pypowsybl
> 
> 
> Current channels:
> 
>     * https://conda.anaconda.org/conda-forge/osx-arm64
> 
>     * https://conda.anaconda.org/conda-forge/noarch
> 
> 
> (if a question doesn't apply, you can delete it)

Hello
Someone will get a mac with a m2 chip next week and we will try to debug it until that we do not have a mac with a mac chip

**Comment by geofjamg** [comment]
We don't provide wheels for Mac ARM, so indeed if you want to use it on Mac ARM, you have to build it yourself. It works, I do it regularly on my laptop. The only thing that has to be changed is the version of Pandas, we depend on 1.3.5 by only ones >= 1.4.0 are compatible with Mac ARM.

To be able to support and upload Mac ARM64 wheels in addition to AMD64 ones we would need:
 - upgrade Pandas to 1.4.x BUT in that case we would lost Python 3.7 support (because Pandas projects do not provide wheels anymore for Python 3.7 since 1.4.0) => @EtienneLt @sylvlecl we have to decide if it is ok or not for us.
 - the most difficult part... there is no GitHub actions worker for Mac ARM (not yet, there is a lot of discussions/complains about this), so there is no simple way to have a centralized build of wheels for Mac ARM like for the other platforms. We would need to build them for instance on my computer which is not a robust/convenient way to make releases. Or maybe an other solution would be to rent a Mac ARM instance on the cloud (there is more and more cloud providers supporting this) and setup an external GitHub action worker.

**Comment by devops-42** [comment]
Hi, 

are there any instructions / how-to's to process "the most difficult part" at least locally? 

Thanks for your help!

**Comment by geofjamg** [comment]
https://github.com/powsybl/pypowsybl#build-from-sources
And
  - replace pandas version in the requirement.txt from 1.3.5 to 1.4.4
  - don't forget to download the mac ARM version: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java11-darwin-aarch64-22.2.0.tar.gz. It is only available from 22.x version of GraalVM not the 21.x one.

**Comment by devops-42** [comment]
Thanks for your response. The install process exits with an error. Steps I've made:

```
wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java11-darwin-aarch64-22.2.0.tar.gz
tar zxf graalvm-ce-java11-darwin-aarch64-22.2.0.tar.gz
mv graalvm-ce-java11-22.2.0 graalvm
export JAVA_HOME=`pwd`/graalvm/Contents/Home
export PATH=`pwd`/graalvm/Contents/Home/bin:$PATH
gu install native-images

git clone --recursive https://github.com/powsybl/pypowsybl.git
cd pypowsybl
pip install --upgrade setuptools pip
vi requirements.txt # <-- changed pandas version to 1.4.4
pip install -r requirements.txt
pip install .
```

The error message is:

```
      ========================================================================================================================
      GraalVM Native Image: Generating 'pypowsybl-java' (shared library)...
      ========================================================================================================================
      
      [1/7] Initializing...                                                                                    (0,0s @ 0,41GB)
      Fatal error: java.lang.IllegalAccessError: class com.powsybl.python.commons.Directives (in unnamed module @0x32428874) cannot access class com.oracle.svm.core.c.ProjectHeaderFile (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.c to unnamed module @0x32428874
          at com.powsybl.python.commons.Directives.getHeaderFiles(Directives.java:22)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.QueryCodeWriter.visitNativeCodeInfo(QueryCodeWriter.java:146)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.QueryCodeWriter.write(QueryCodeWriter.java:91)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:101)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:554)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1617)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1073)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:896)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
          at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

**Comment by devops-42** [comment]
Update: I could compile it finally with an additional environment variable:

```
USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=false pip install .
```

Remark: This environment variable won't be supported in future releases of GraalVM (see https://www.graalvm.org/release-notes/22_2/#native-image).
