### ISSUE TITLE
CGMES Export logs of not a defined slack bus even after power flow has converged

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/pypowsybl#488]
* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Currently, after the network is loaded and a power flow is correctly run, which means that the slack bus is defined, the cgmes exporter logs a warning that the slack bus was not defined for the same synchronous component.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

import pypowsybl as pb

pb.loadflow.run_ac(n)

Result : 

INFO:powsybl:Ac loadflow complete on network {CC0 SC0} (result=AcLoadFlowResult(outerLoopIterations=4, newtonRaphsonIterations=8, newtonRaphsonStatus=CONVERGED, slackBusActivePowerMismatch=-0.7888611013215696, distributedActivePower=292.7221519996114))

[ComponentResult(connected_component_num=0, synchronous_component_num=0, status=CONVERGED, iteration_count=8, slack_bus_id='756bbd53-5956-47a1-8af4-96552df79251_0', slack_bus_active_power_mismatch=-0.7888611013215696, distributed_active_power=292.7221519996114)]

Now,

n.dump("network.cgmes",format="CGMES")

Leads to following Info: 

INFO:powsybl:Synchronous component  0 does not have a defined slack bus: it is ignored

* **What is the expected behavior?**

The INFO is wrong as the slack bus id is defined and power flow was already run.

* **What is the motivation / use case for changing the behavior?**

Clarity and transperency 

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
There is a writeSlackBus option in LoadFlowParameters that is false by default that allows to store in the network the selected slack bus during LF. Passing this option to true should solve your issue.
