### ISSUE TITLE
Network element "deep removal"

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#534]
* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

The removal of elements, for example a load, leaves the topology in a state that can be weird from the user point of view: it leaves "dangling" breakers etc.

* **What is the expected behavior?**

powsybl now proposes a `NetworkModification` to do a deep removal which will also removes that kind of connection elements.
We should interface it, in addition to the existing "remove" method.

**Comment by AnkurArohi** [comment]
@sylvlecl 
I do not understand what you mean by
"which will also removes that king of connection elements."

**Comment by sylvlecl** [comment]
(I meant kin**d** there was a typo :) )

I meant that typically, a load (but any other element like a line, a generator ...) will be connected to a busbar section by at least a breaker and a disconnector. This is what we call "feeder bays", for example now we have methods such as `create_load_bay` which creates at the same time a load, a breaker, and a disconnector to connect the load to a busbar.

The new "deep removal" method would remove those 3 elements: the load, the breaker, and the disconnector.
