### ISSUE TITLE
Expose secondary voltage control extensions

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#558]
* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the expected behavior?**

We should be able to manipulate secondary voltage control extension introduced in https://github.com/powsybl/powsybl-core/pull/2436 

* **What is the motivation / use case for changing the behavior?**

Being able to simulate secondary voltage control with open loadflow.

* **Implementation notes**

Things that may need some design work:
- it's an extension of `Network`, is it an issue with the existing mechanism ?
- the extension has nested objects: the natural representation would be multiple tables.
  Should we implement multiple "DataframeProvider", instead of juste one, for this extension ?

**Comment by EtienneLt** [comment]
done with #564
