### ISSUE TITLE
CGMES Exporter ends up in error 

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/pypowsybl#587]
* **Do you want to request a *feature* or report a *bug*?**
BUG

* **What is the current behavior?**
currently when one loads the network and merges two networks with different format types (UCTE,CGMES), the cgmes exporter, dump leads to an error and only EQ File is generated.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

network_uct = pypowsybl.network.load(
      "F0R.UCT"
  )
network_cim = pypowsybl.network.load(cgmes.zip"
  )

network_cim.merge(network_uct)

network.dump(self.path + "/cgmes.zip", format='CGMES')

path is an adress to a local folder

* **What is the expected behavior?**

All 4 profiles should be exported 

* **What is the motivation / use case for changing the behavior?**

- BUG

* **Please tell us about your environment:**
  - PowSyBl Version: ... 0.20
  - OS Version: ... Fedora

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by miovd** [comment]
Hi @AnkurArohi. Can you retry wit `network.dump(self.path + "/cgmes", format='CGMES')`? It might be an error due to the output format: CGMES exporter does not zip its files, it exports 4 different files and the name passed should be the base name.

**Comment by AnkurArohi** [comment]
Hi @miovd Thanks for your reply, yes it has worked.
