### ISSUE TITLE
Ability to read a set of network from a zip without unzipping

### ISSUE THREAD

**Issue by nicolaslhuillier** [powsybl/pypowsybl#606]
### Describe the current behavior

Currently not possible due to an error :
AttributeError: 'ZipExtFile' object has no attribute '__fspath__'

### Describe the expected behavior

Try not using this property so that it works.
Available properties are listed here 👍 

### Describe the motivation

Can leave the network files in the zip (easier to manipulate and store)

### Extra Information

Code example :
import zipfile
with zipfile.ZipFile('archive.zip') as archive:
  for network_file in archive.namelist():
    if network_file.endswith('xiidm'):
      with archive.open(network_file) as f:
        n = pp.network.load(f)

**Comment by nomont** [comment]
Hi Nicolas,
What happens if the archive contains file paths starting with "../../../../" (classical trick to deploy malwares)?
Nicolas.

**Comment by nicolaslhuillier** [comment]
I am not able to say. But if we rely on standard python libraries it should be as safe as they are.

**Comment by EtienneLt** [comment]
will be resolved by https://github.com/powsybl/pypowsybl/issues/401

**Comment by EtienneLt** [comment]
done with https://github.com/powsybl/pypowsybl/pull/672
