### ISSUE TITLE
[Doc] Add docstrings and generate a public doc

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#61]
Yes, docstrings is essential for wide usage of the library. It was on my TODO list but I did had time to start anything.
Also it would be great to have a readthedocs.io with a user doc and part made of generated doc from doncstrings. readthedocs.io seems to be a common way to document Python libraries (https://pandasguide.readthedocs.io/en/latest/ for instance)

_Originally posted by @geofjamg in https://github.com/gridsuite/gridpy/pull/60#discussion_r606149205_

**Comment by geofjamg** [comment]
As a first step I added an empty Sphinx doc  to the repo and an automatic build to https://gridpy.readthedocs.io/en/latest/?badge=latest (#64)

**Comment by sylvlecl** [comment]
Closing this old issue:
we have now a "good enough" base documentation, to be improved and maintained on the long run.
