### ISSUE TITLE
Bug with PerUnitView + 3 windings transformers strike again: they are weirdly represented in cdf format and not present in powsybl

### ISSUE THREAD

**Issue by BDonnot** [powsybl/pypowsybl#642]
### Describe the current behavior

When loading the grid with:

```python
import pypowsybl as pp
network = pp.network.create_ieee14()
```

There are 2 powerlines with parmeters that differ from the matpower files (original file here http://labs.ece.uw.edu/pstca/pf14/ieee14cdf.txt matpower file here https://matpower.org/docs/ref/matpower5.0/case14.html)

In these file, we can "see" line 0068 and 0069 of https://matpower.org/docs/ref/matpower5.0/case14.html that powerlines connecting bus 7 to 8 and 7 to 9 (matpower convention, so 6 to 7 and 6 to 8 in python) do have `r=0` and `b=0`

But if we look at the corresponding line in the pypowsybl network: 
```python
network.get_lines().loc[["L7-8-1", "L7-9-1"]]
```
we indeed have `r=0` but we have b1 != 0. and b2 != 0.

And also, only for these 2 powerlines we got `b1 != b2` (which is weird)

And finally, if we "per unit correctly" the `x` we end up with (for these 2 lines):
```python
df_line = net.get_lines()
branch_from_kv = net.get_voltage_levels().loc[df_line["voltage_level1_id"].values]["nominal_v"].values
sn_mva_ = 100.
(df_line["x"].values / branch_from_pu)[[10,11]]
# gives array([0.25164286, 0.09429429])
```
Which is not [0.17615, 0.11001] as found in the matpower file.

With the chosen voltages, there should be:
```python
df_line["x"].values[[10,11]] == [0.34525399999999995, 0.2156196]  # correct given the per unit system
```
and not
```python
df_line["x"].values[[10,11]] == [0.49322  , 0.1848168]  # wrong
```

### Describe the expected behavior

One test could be added for the ieee14 :

```python
import pypowsybl as pp
network = pp.network.create_ieee14()

# get the reference data
ref_x = np.array([0.05916999999999999, 0.22304, 0.19797, 0.17632, 0.17388, 0.17102999999999996, 0.04211, 0.19890000000000002, 0.25581, 0.13027, 0.17614999999999997, 0.11001, 0.0845, 0.27038, 0.19207, 0.19987999999999997, 0.34802])
ref_r = np.array([0.01938, 0.05403, 0.04698999999999999, 0.058109999999999995, 0.056949999999999994, 0.06701, 0.01335, 0.09498, 0.12291, 0.06615000000000001, 0.0, 0.0, 0.03180999999999999, 0.12711000000000003, 0.08205, 0.22092, 0.17093])
ref_b = np.array([0.0528, 0.0492, 0.0438, 0.034, 0.0346, 0.0128] + 11* [0.])

# compute the equivalent from the pypowsybl grid (per unit yeah...)
df_line = net.get_lines()
branch_from_kv = net.get_voltage_levels().loc[df_line["voltage_level1_id"].values]["nominal_v"].values
sn_mva_ = 100.
branch_from_pu = branch_from_kv * branch_from_kv / sn_mva_

# check x
assert np.abs(df_line["x"].values / branch_from_pu  - ref_x).max() <= 1e-6, "error for x"
# check r
assert np.abs(df_line["r"].values / branch_from_pu - ref_r).max() <= 1e-6, "error for r"
# check b
assert np.abs( (df_line["b1"].values+df_line["b2"].values) * branch_from_pu - ref_b).max() <= 1e-6, "error for r"

# check g (not in any matpower files, so all 0)
assert np.abs(df_line["g1"].values).max() <= 1e-6, "error for b1"
assert np.abs(df_line["g2"].values).max() <= 1e-6, "error for b1"
```

And I would also personnally check that b1 == b2 (because only "b" is given in matpower so it's surprising for me that we end up with powerlines having b1 != b2) but that's only my humble opinion.

### Describe the steps

To fix the issue, you can run:

```python
vn = 14.
network.update_lines(id=["L7-8-1", "L7-9-1"],
                                  x=[0.17615 * vn*vn/100., 0.11001 * vn*vn/100.],
                                  b1=[0., 0.],
                                  b2=[0., 0.])
```

### Environment

I think it's all version on pypowsybl on all systems.

I am using pypowsybl 0.24.0 on ubuntu 20.04 with python 3.8.

**Comment by geofjamg** [comment]
Sorry for my late answer.
One important thing to be aware in pypowsybl (and more generally in powsybl with IIDM model) is that data are always expressed in engineering units and never in per units like in IEEE CDF or Matpower model. 

When assigning arbitrary nominal voltage to original IEEE case like it is done in Matpower case, we are making some lines to not have same nominal voltages ate both sides and this is the case for the 2 lines you mentioned. In a per unit system it has not impact but when converting the engineering unit system (like we are doing when converting from IEEE to IIDM) we end up to some weird values of charging susceptance: large and asymmetric values. From a mathematical point of view this is absolutely correct even if it looks unusual values (I can share the mathematical demonstration if you want).

This is easy to convince ourself that IIDM model is equivalent to original IEEE one by just running a power flow and comparing state variables to original IEEE ones.

```python
>>> import pypowsybl as pp
>>> import pandas as pd
>>> n = pp.network.create_ieee14()
>>> before = n.get_buses(attributes=['v_mag'])
>>> pp.loadflow.run_ac(n)
[ComponentResult(connected_component_num=0, synchronous_component_num=0, status=CONVERGED, iteration_count=3, slack_bus_id='VL1_0', slack_bus_active_power_mismatch=-0.006730108617958308, distributed_active_power=0.0)]
>>> after = n.get_buses(attributes=['v_mag'])
>>> pd.concat([before, after], axis=1)
          v_mag       v_mag
id
VL1_0   143.100  143.100000
VL2_0   141.075  141.075000
VL3_0   136.350  136.350000
VL4_0   137.565  137.385566
VL5_0   137.700  137.634371
VL6_0    12.840   12.840000
VL7_0    14.868   14.861273
VL8_0    21.800   21.800000
VL9_0    12.672   12.671181
VL10_0   12.612   12.611816
VL11_0   12.684   12.682878
VL12_0   12.660   12.662263
VL13_0   12.600   12.604581
VL14_0   12.432   12.426359
``` 

As you can see voltage magnitudes calculated by OLF is very close to the one coming from IEEE file.

**Comment by BDonnot** [comment]
I did not notice indeed that these lines connect buses with different voltages. 

So shouldn't they be modelled as transformer in pypowsybl ? (this is how pandapower is doing it by the way)

> When assigning arbitrary nominal voltage to original IEEE case like it is done in Matpower case

This is a problem for the case 14 but not for the 30 or the 118 were similar issues arise (see #645  or #646) Indeed for the later 2 cases voltage are given in the original file (and are not the correct one in pypowsybl for ieee 118 see #644)

Anyway if you don't think these are "problem" worth looking at then you can close all the related issues :-)

**Comment by BDonnot** [comment]
Ok I think i got the explanation for the ieee14 at least.

# for ieee 14

In fact, as you can see here http://labs.ece.uw.edu/pstca/pf14/pg_tca14fig.htm the buses 4, 7, 8, 9 are a representation in a bus-branch model of a 3 windings transformer.

So i guess all voltages levels VL4, VL7, VL8 and VL9 are on the same substation (taking powsybl definition here) and that indeed "powerlines" from 7 to 8 and from 7 to 9 can (should in my opinion) be modeled as 2 winding transformers and not powerlines as it is done today (though you convinced me that at the end it gives the same results)

I try to change after the network is loaded with

```python
        df = pd.DataFrame()
        vn = np.array([20., 12.])
        convert_pu = vn*vn/100.
        df.index = ["T7-8-1", "T7-9-1"]
        df["r"] = [0., 0.] * convert_pu
        df["x"] = [0.17615, 0.11001] * convert_pu
        df["b"] = [0., 0.]
        df["g"] = [0., 0.]
        df["voltage_level1_id"] = ["VL7", "VL7"]
        df["voltage_level2_id"] = ["VL8", "VL9"]
        df["bus1_id"] = ["VL7_0", "VL7_0"]
        df["bus2_id"] = ["VL8_0", "VL9_0"]
        network.create_2_windings_transformers(df)
```
But i got the error :
```
pypowsybl._pypowsybl.PyPowsyblError: Could not create transformer T7-8-1: both voltage ids must be on the same substation
```
(which make total sense)

Then i tried to change the substations in the voltage levels:

```python
network.update_voltage_levels(id=["VL8"], substation_id=["S4"])
```
Which leads to:
```
*** pypowsybl._pypowsybl.PyPowsyblError: Series 'substation_id' is not modifiable.
```
Which is probably due to a technical reason.

I guess i'll have to stick with different ieee14 for now then.

# for ieee30

Exactly the same issue, there are indeed 2 "3 windings transformers" in the original published grid see (http://labs.ece.uw.edu/pstca/pf30/pg_tca30fig.htm) that are: 
- buses 4-12-13
- buses 6-9-11-10

So again for this case I think if the lines "L9-11-1", "L9-10-1", "L12-13-1" in pypowsybl would be represented as simple 2 winding trafos then the grid would be closer to rthe one published 

# for ieee118

The image of the grid is rather blurry  http://labs.ece.uw.edu/pstca/pf118/pg_tca118fig.htm but i guess it's the same problem, and also the lines "L86-87-1" and  "L68-116-1" are probably part of a 3 windings trafo (which is not tagged as such in the bus branch matpower format...).

One quick (and usual) fix would be of course to convert these 2 powerlines to 2 windings transformers in powsybl. That would lead to a more accurate grid representation of these 3 test cases in powsybl in my opinion.

**Comment by geofjamg** [comment]
In IIDM we have forbidden the creation of transformer outside of substation containers so that we cannot replace lines with different nominal voltage at both sides by transformers. So this is why we have such strange lines and indeed that would have been better to replace them by a transformer to have a cleaner modelling.

**Comment by BDonnot** [comment]
Ok sorry to bother with this again.

I totally got that the system is equivalent is running a powerflow from the test case. But I recently found the work in pypowsybl about per unit that offers a way to "correctly per unit" the grid and expose the attributes.

```python
import pypowsybl.perunit as pypow_pu
pu_view =  pypow_pu.PerUnitView(network)
pu_view.get_lines()
```

In my opinion, this grid should be the initial cdf grid that is given in per unit system. Though (as expected) the two powerlines (for the case14) have value for b1 and b2 that are not consistent with the initial cdf file leading to this "consistency" problem.

But maybe that is linked to the fact that the "per unit" done in the python wrapper by `PerUnitView` is not the one done in OLF during the computation. 

Or else I don't see (I plea guilty on lack of knowledge about that) how a different matrix Ybus (obtained after the per unit of the lines and transformers basically - and some other stuff) would lead to the same results (but I totally understand and acknowledge it gives the same results)

**Comment by BDonnot** [comment]
Yes indeed, the code for the "per unit to engineering units" in powsybl here:
 https://github.com/powsybl/powsybl-core/blob/266442cbbd84f630acf786018618eaa3d496c6ba/ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfImporter.java#L347
 is different from the formula given in the `PerUnitView` there 
https://github.com/powsybl/pypowsybl/blob/41c5074aa0b4b9a23fec0cdc8e5488267bc9a5a8/pypowsybl/network/impl/perunit.py#L111 
The part looking like  `(1- v1 / v2) * x` (or something like that) is missing for g and b. Of course it's 0. when powerlines connect nodes with same voltage but otherwise it's different (this would not cause any trouble if the ieee / cdf importer converted these lines to trafo but as it does not there is an issue with the PerUnitView)

**Comment by geofjamg** [comment]
@BDonnot you are right the `PerUnitView` is not correct. I will fix it soon.

**Comment by BDonnot** [comment]
I used this formula to create the per unit view (net being a pypowsybl network):
```python
    sn_mva_ = 100.

    df_line = net.get_lines()
    branch_from_kv = net.get_voltage_levels().loc[df_line["voltage_level1_id"].values]["nominal_v"].values
    branch_to_kv = net.get_voltage_levels().loc[df_line["voltage_level2_id"].values]["nominal_v"].values
    v1 = branch_from_kv
    v2 = branch_to_kv

    line_r = sn_mva_ *  df_line["r"].values / v1 / v2
    line_x = sn_mva_ *  df_line["x"].values / v1 / v2
    tmp_ = np.reciprocal(df_line["r"].values + 1j*df_line["x"].values)
    b1 = df_line["b1"].values * v1*v1/sn_mva_ + (v1-v2)*tmp_.imag*v1/sn_mva_
    b2 = df_line["b2"].values * v2*v2/sn_mva_ + (v2-v1)*tmp_.imag*v2/sn_mva_
    g1 = df_line["g1"].values * v1*v1/sn_mva_ + (v1-v2)*tmp_.real*v1/sn_mva_
    g2 = df_line["g2"].values * v2*v2/sn_mva_ + (v2-v1)*tmp_.real*v2/sn_mva_

    # the per unit table should contain line_r, line_x, b1, b2, g1 and g2
```

I can do a PR if you want but i'm not sure I have all my github environment set up (probably missing the "verified" stuff - my certificate has expired)

**Comment by EtienneLt** [comment]
done with #651
