### ISSUE TITLE
Wrong nominal voltage for almost all voltage level in IEEE 118

### ISSUE THREAD

**Issue by BDonnot** [powsybl/pypowsybl#644]
### Describe the current behavior

Some voltage levels are not consistent between pypowsybl and the reference ieee 118 data.

I think there is a "mislabelling" between the voltage levels of the original file here http://labs.ece.uw.edu/pstca/pf118/ieee118cdf.txt (or in the matpower format https://matpower.org/docs/ref/matpower5.0/case118.html)

```python
import numpy as np
import pypowsybl as pp
network = pp.create_ieee118()
network.get_voltage_levels()
```

The reference voltages are:
```python
ref_v = np.array([138,138,138,138,138,138,138,345,345,345,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,345,138,138,138,345,138,138,138,138,138,138,138,345,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,345,345,345,138,138,345,138,138,138,138,138,138,138,138,138,138,138,138,345,138,138,138,138,138,161,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138])
```

And if we do:

```python
np.unique(network.get_voltage_levels()["nominal_v"].values, return_counts=True)
# => (array([138., 161., 345.]), array([ 11, 106,   1]))
# BUT
np.unique(ref_v, return_counts=True)
# => (array([138, 161, 345]), array([106,   1,  11]))
```

I would say the voltages are correct but in pypowsybl you need to change 138kV to 345. kV, 161 kV to 138 kV and 345 kV to 161 kV in order to match the standard ieee 118 grid.

### Describe the expected behavior

You can add the test suite:

```python
assert np.all(network.get_voltage_levels()["nominal_v"].values == ref_v)
```
in pypowsybl to make sure this bug does not re appear.

**Comment by geofjamg** [comment]
Nominal voltage are assigned like this:
```java
            if (ieeeCdfBus.getName().endsWith("V1")) {
                return 138;
            } else if (ieeeCdfBus.getName().endsWith("V2")) {
                return 161;
            } else if (ieeeCdfBus.getName().endsWith("V3")) {
                return 345;
            }
```
So this is not correct ?

**Comment by BDonnot** [comment]
From the matpower case file (https://matpower.org/docs/ref/matpower5.0/case118.html)

Bus 1 has a basekv of `138` so i guess "V2" should be associated with 138 kV
Similarly bus 8 has a basekv of 345 so i would associate "V1" with 345
And so v3 with 161:

```python
            if (ieeeCdfBus.getName().endsWith("V1")) {
                return 345;
            } else if (ieeeCdfBus.getName().endsWith("V2")) {
                return 138;
            } else if (ieeeCdfBus.getName().endsWith("V3")) {
                return 161;
            }
```

**Comment by geofjamg** [comment]
https://github.com/powsybl/powsybl-core/pull/2708
