### ISSUE TITLE
Wrong parameters for 2 powerlines for ieee118

### ISSUE THREAD

**Issue by BDonnot** [powsybl/pypowsybl#645]
### Describe the current behavior

This issue is similar to #642 and it might have the same root cause, or not.

For the case118 (with the wrong voltages, see issue #644) 2 powerlines do not have the right parameters: they have some non null `g` (which is always 0. in matpower case file) and different r, x and b that the original file http://labs.ece.uw.edu/pstca/pf118/ieee118cdf.txt (or the matpower version here https://matpower.org/docs/ref/matpower5.0/case118.html)

I noted this issue concerned 2 powerlines: "L86-87-1" "L68-116-1" . A quick fix is to update their parameters (NB: this per unit is considering the "wrong" voltage levels for this grid in pypowsybl, if issue 644 is fixed new parameters will need to be computed):

```python
import pypowsybl
network = pypowsybl.create_ieee118()
vn = np.array([161.0, 138.0])
from_pu = vn*vn*0.01
network.update_lines(id=["L86-87-1", "L68-116-1"],
                                        r=np.array([0.02828 , 0.00034]) * from_pu,
                                        x=np.array([0.2074 , 0.00405]) * from_pu,
                                        b1=np.array([0.0445, 0.164]) / 2. / from_pu,
                                        b2=np.array([0.0445, 0.164]) / 2. / from_pu,
                                        g1=np.array([0., 0.]),
                                        g2=np.array([0., 0.]),
)
```

In this setting, these 2 lines will have the same parameters as in the normal ieee118

**Comment by geofjamg** [comment]
I think this is the same as for #642

**Comment by BDonnot** [comment]
Yes and you are correct these lines look like transformers, maybe that would be better to model them as such without having to add some g's and b's (and it's closer to what it appears to be)

**Comment by BDonnot** [comment]
I'm closing this as we might discuss it in the #642 instead
