### ISSUE TITLE
Wrong parameters for 3 powerlines for ieee30

### ISSUE THREAD

**Issue by BDonnot** [powsybl/pypowsybl#646]
### Describe the current behavior

The powerlines "L9-11-1", "L9-10-1", "L12-13-1" have different parameters in powsybl and in the original matpower /cdf file (https://matpower.org/docs/ref/matpower5.0/case_ieee30.html or http://labs.ece.uw.edu/pstca/pf30/ieee30cdf.txt)

(Quite similarly to the previous issues on ieee 118 and ieee 14), to fix the issue, you can do:

```python
import pypowsybl as pp
network = pp.network.create_ieee30()
vn = np.array([1.0, 1.0, 33.0])
to_pu = vn*vn*0.01
network.update_lines(id=["L9-11-1", "L9-10-1", "L12-13-1"],
                                  r=np.array([0., 0., 0.]) * to_pu,
                                  x=np.array([0.208, 0.11, 0.14]) * to_pu,
                                  b1=np.array([0., 0., 0.]) / 2. / to_pu,
                                  b2=np.array([0., 0., 0.]) / 2. / to_pu,
                                  g1=np.array([0., 0., 0.]),
                                  g2=np.array([0., 0., 0.]),
        )
```

### Describe the expected behavior

One "quick and dirty" solution would be to clearly mark in the documentation that the grid is inspired from the ieee 30 with some modifications (and list them: so give the r, x, b and g on both side of the 3 powerlines concerned).

The better longer term solution would be fix the grid read from powsybl / pypowsybl of course.

**Comment by geofjamg** [comment]
I think this is the same as for #642, the mentioned lines have a different nominal voltage at both side causing when converting to an engineering unit system large and asymmetrical charging suce-tance values.

**Comment by BDonnot** [comment]
I'm closing this as we might discuss it in the #642 instead
