### ISSUE TITLE
Support a more pythonic way of checking if a powerflow diverges

### ISSUE THREAD

**Issue by BDonnot** [powsybl/pypowsybl#648]
### Describe the current behavior

Today, when running a powerflow you get a result in the form of an "enum". And if you want to check whether a given component (say the first for the example) converges you need to (unless I missed something in the doc):

```python
res_pp = lf.run_ac(network)
if res_pp[0].status == pp._pypowsybl.LoadFlowComponentStatus.CONVERGED:
    do something
```

### Describe the expected behavior

It would be awesome (though I agree it's pure laziness) and more "pythonic" to be able to write something like this:
```python
res_pp = lf.run_ac(network)
if res_pp[0].status :
    do the same thing
```

### Describe the motivation

This is to make the API both more pythonic and easier to use, especially for "newbies" like myself.

You can use for example the dunder `__bool__` method here : https://docs.python.org/3/reference/datamodel.html#object.__bool__

**Comment by geofjamg** [comment]
Thanks for the feedback. Indeed that would be more convenient. I will implement this for next release.

**Comment by BDonnot** [comment]
The implementation can even be done in python wrapper:

```python
import pypowsybl as pp

# implementation
def converged(self):
    return self == pp._pypowsybl.LoadFlowComponentStatus.CONVERGED
setattr(pp._pypowsybl.LoadFlowComponentStatus, "__bool__", converged)

# test
conv = pp._pypowsybl.LoadFlowComponentStatus.CONVERGED
not_conv = pp._pypowsybl.LoadFlowComponentStatus.MAX_ITERATION_REACHED


if conv:
    print("Convergence correctly detected")
else:
    print("ERROR: convergence not detected")
assert conv

if not_conv:
    print("ERROR: divergence not detected")
else:
    print("Divergence correctly detected")
assert not not_conv
```

It outputs:

```
Convergence correctly detected
Divergence correctly detected
```

**Comment by EtienneLt** [comment]
done with #652
