### ISSUE TITLE
Integration of new version of OpenReac

### ISSUE THREAD

**Issue by annetill** [powsybl/pypowsybl#665]
### Describe the current behavior

For specific voltage `VoltageLimitOverride` (Java), we map currently to python like this:
````
params.add_specific_voltage_limits({"vl_id": (0.5, 1.2)}) // vl id, minVoltage, maxVoltage
(see unit tests)
````
Where `minVoltage` and `maxVoltage` are the relative difference between IIDM voltage limits (low for min and high for max). 
new Limit of voltage level vl_id = vl.getLow(High)VoltageLimit() + min(max)Voltage

### Describe the expected behavior

Now, the voltage limits override has changed in Java to
````
VoltageLimitOverride(String voltageLevelId, VoltageLimitType type, boolean isRelative, double limit)
````
with voltage limit type low or high. 

I think that in pypowsybl we can imagine a dataframe:
````
params.add_specific_voltage_limits({"vl_id": (0.5, true, 1.2, true)}) // vl id, minVoltage, relative, maxVoltage, relative
````
or maybe:
````
params.add_specific_voltage_limits({"vl_id": (0.5, 1.2, true, true)}) // vl id, minVoltage, maxVoltage, relative for min, relative for max
params.add_specific_voltage_limits({"vl_id": (380, 420, false, false)}) // for an absolute change.
params.add_specific_voltage_limits({"vl_id": (380, 0, false, true)}) // for one side change.
````

**Comment by pjeanmarie** [comment]
-> addSpecificVoltageLimits:
Before:
` OpenReacParameters addSpecificVoltageLimits(Map<String, VoltageLimitOverride> specificVoltageLimits)
`
example of call:
```
double lowerPercent = node.get("lower").asDouble();
double upperPercent = node.get("upper").asDouble();
openReacParameters.addSpecificVoltageLimits(Map.of(voltageId, new VoltageLimitOverride(lowerPercent, upperPercent)));
```
and with  VoltageLimitOverride:
```
private final double deltaLowVoltageLimit;
private final double deltaHighVoltageLimit;
```
After:
`public OpenReacParameters addSpecificVoltageLimits(List<VoltageLimitOverride> specificVoltageLimits)
`
example of call:
```
double lower = node.get("lower").asDouble();
double upper = node.get("upper").asDouble();
List<VoltageLimitOverride> voltageLimitOverrides = new ArrayList<>();
voltageLimitOverrides.add(new VoltageLimitOverride(voltageId, VoltageLimitOverride.VoltageLimitType.LOW_VOLTAGE_LIMIT, true, lower));
voltageLimitOverrides.add(new VoltageLimitOverride(voltageId, VoltageLimitOverride.VoltageLimitType.HIGH_VOLTAGE_LIMIT, true, upper));
openReacParameters.addSpecificVoltageLimits(voltageLimitOverrides);
```
and with  VoltageLimitOverride:
```
private final VoltageLimitType type; // indicates if the override is done on low or on high voltage limit
private final boolean isRelative; // if true, override is relative. if false, override is absolute
private final double limit; // value of the limit override
private final String voltageLevelId;
```

**Comment by pjeanmarie** [comment]
-> add_specific_voltage_limits in python:

Before:
`def add_specific_voltage_limits(self, limits: Dict[str, Tuple[float, float]]) -> None
`
with probably (based on before of addSpecificVoltageLimits):
`limits: Dict[voltageId, Tuple[deltaLowVoltageLimit, deltaHighVoltageLimit]]
`
where Dict is java Map and Tuple is VoltageLimitOverride

After, following exactly java code (see after of addSpecificVoltageLimits), it could be:
`def add_specific_voltage_limits(self, limits: List[Tuple[str, Enum, Boolean, float]]) -> None
`
with:
`limits: List[Tuple[voltageLevelId, type, isRelative, limit]]
`
where List is java List and Tuple is VoltageLimitOverride
--> this solution is not the chosen one

**Comment by pjeanmarie** [comment]
If in the new addSpecificVoltageLimits parameter which is a List, we need that this list contains 2 elements by voltageId, one of this element with type "low" and the other one with type "high", and if we want that to be reinforced by the type choosen for add_specific_voltage_limits parameter, then List[Tuple[voltageLevelId, type, isRelative, limit]] is too permissive and we need to choose something else, for instance:

**Comment by pjeanmarie** [comment]
Notes about chosen solution:
It allows to:
- give only low or only high limit to a voltage level as it is now possible with the new java api
- use the new "is relative" parameter
- instead of the java API addSpecificVoltageLimits which have enum (LOW_VOLTAGE_LIMIT, HIGH_VOLTAGE_LIMIT) as a parameter, the python API is splitted in two functions add_specific_low_voltage_limits and add_specific_high_voltage_limits
