### ISSUE TITLE
Reduce Network is not working

### ISSUE THREAD

**Issue by vlgmarchesini** [powsybl/pypowsybl#736]
### Describe the current behavior

When I call the function network.reduce, it pops out an error:
'PyPowsyblError: Parent tie line WTREBI5  XTR_HN51 1 + XTR_HN51 0HNOVI51 1 should be removed before the child dangling line'

Regardless of filtering by ids, voltage levels, and setting 'with_dangling_lines' to True or False, the error persists.

I tested with several different Common Grid Model uct files and the same error appears.
Once I remove all tielines that are not in the interest area. It works...

### Describe the expected behavior

I would expect to reduce the problem size (interest area) an decrease time to run load flow and security analysis.

### Extra Information

I think it is a bug in the wrapper.

**Comment by annetill** [comment]
https://github.com/powsybl/powsybl-core/issues/3026

**Comment by geofjamg** [comment]
@vlgmarchesini this issue will be solved in next release thanks to https://github.com/powsybl/powsybl-core/pull/3038

**Comment by geofjamg** [comment]
Solved
