### ISSUE TITLE
Security Analysis module gives wrong loadflow results on PST outages

### ISSUE THREAD

**Issue by nicow-elia** [powsybl/pypowsybl#758]
### Describe the current behavior

Using DC loadflows, when outaging a PST through pypowsybl.security, the loadflow results are incorrect. Using net.remove_elements to remove the PST completely from the grid gives the correct post-outage loadflows, however the result in the security module are different. I am reasonably certain that the results using remove_elements are the correct ones as they match with our internal lodf based computation.

### Describe the expected behavior

Loadflows p1_sec and p1_ref are equal up to floating point precision.

### Describe the steps

Code to replicate available [in this gist](https://gist.github.com/nicow-elia/37c77f8ca7dd71c687093ea7f26a5672).

### Environment

- pypowsybl 1.3.1 (latest from pip, I think it should relate to 1.5.1 in this repository but pip freeze gives 1.3.1 as result)
- Python 3.10

### Relevant Log Output

<img width="561" alt="image" src="https://github.com/powsybl/pypowsybl/assets/129943275/775429c1-cbdb-4d93-9141-a6cd71f8e3e7">

**Comment by jeandemanged** [comment]
Hi @nicow-elia ,

This should be fixed starting from PyPowSyBl 1.6.0, did you have the opportunity to re-check ?

Thanks for feedback

**Comment by geofjamg** [comment]
Indeed, tested with 1.8.1 there is no difference anymore.
