### ISSUE TITLE
Add the parameter EdgeInfoDisplayed

### ISSUE THREAD

**Issue by unetablettedechocolat** [powsybl/pypowsybl#769]
### Describe the current behavior

The parameter EdgeInfoDisplayed exists in SvgParameters (wich is instanciated in NadParameters) in powsybl-diagram. It chooses the value displayed near the arrows (active power, reactive power, or current). It doesn't exist in PyPowSyBl.

### Describe the expected behavior

Add a new NadParameter attribute: edge_info_displayed that allow to choose the value displayed.

### Describe the motivation

Customize the edge info displayed

**Comment by So-Fras** [comment]
Dealt with in #773
