### ISSUE TITLE
Add the parameter display_current_feeder_info

### ISSUE THREAD

**Issue by unetablettedechocolat** [powsybl/pypowsybl#774]
### Describe the current behavior

displayCurrentFeederInfo exists in SvgParameters class (single-line-diagram-core) of powsybl-diagram, allowing to display current value. It does not exist in pypowsybl.

### Describe the expected behavior

Add the parameter display_current_feeder_info in pypowsybl

### Describe the motivation

customize single line diagrams

**Comment by So-Fras** [comment]
Dealt with in #785
