### ISSUE TITLE
add units parameters (activePowerUnit, reactivePowerUnit, currentUnit)

### ISSUE THREAD

**Issue by unetablettedechocolat** [powsybl/pypowsybl#789]
### Describe the current behavior

activePowerUnit, reactivePowerUnit and currentUnit exist in SvgParameters of powsybl-diagram, displaying units with feeder info

### Describe the expected behavior

add these parameters in pypowsybl

### Describe the motivation

display units of feeder info

**Comment by jeandemanged** [comment]
done in https://github.com/powsybl/pypowsybl/pull/799

closing
