### ISSUE TITLE
Optional dangling line generation part

### ISSUE THREAD

**Issue by annetill** [powsybl/pypowsybl#793]
### Describe the current behavior

A dangling line can have a generation part. It seems that these information are not exposed in pypowsybl. 

### Describe the expected behavior

Should be exposed.

**Comment by HugoKulesza** [comment]
@geofjamg should we add these new informations as optional columns in the current dangling lines dataframe or in a new distinct dataframe ?

**Comment by geofjamg** [comment]
As this is a one to one relation between dangling line and generation object I would merge it as optional columns in dangling line dataframe.

**Comment by AnkurArohi** [comment]
opional columns in dangling öine dataframe regarding to the generation attributes would be very helpful, so that one can change the attributes of maxp,minp, voltage regulation and the type "equivalentinjection" or "ExternalNetworkInjection"
