### ISSUE TITLE
Add the possibility to update pairing key for dangling lines

### ISSUE THREAD

**Issue by HugoKulesza** [powsybl/pypowsybl#810]
### Describe the current behavior

Currently, it is not possible to modify the pairing key (and its deprecated equivalent ucte-x-node-code) of a dangling line using the method update_dangling_lines.

### Describe the expected behavior

We should be able to modify the paring key in the update method.

### Describe the motivation

This evolution seems especially useful when creating dangling lines on a network using the "reduce" method with 'with_dangling_lines" parameter set.

**Comment by tso-martin** [comment]
Dear @HugoKulesza , would it be possible to make the attribute bus_breaker_bus_id updateable too?

**Comment by colineplqt** [comment]
> Dear @HugoKulesza , would it be possible to make the attribute bus_breaker_bus_id updateable too?

Hello, this attribute is already updatable, I will add it to the documentation. Are you experiencing any problems with it ?

**Comment by tso-martin** [comment]
@colinepiloquet : Thank you, an update in the documentation will do. The update of the bus_breaker_bus_id works fine.
