### ISSUE TITLE
Integration of latest changes in the flow decomposition

### ISSUE THREAD

**Issue by colineplqt** [powsybl/pypowsybl#828]
### Describe the expected behavior

It seems that the flow decomposition changed a lot on powsybl-entsoe side, would it be possible to do the adaptation in pypowsybl? 
I've seen a couple of breaking changes. It would be really great to integrate them in pypowsybl. 

### Describe the motivation

Then we would be able to update pypowsybl to the latest dependencies.

**Comment by caioluke** [comment]
Sure, I can update pypowsybl's flow decomposition algorithm :)

**Comment by colineplqt** [comment]
> Sure, I can update pypowsybl's flow decomposition algorithm :)

Thank you very much. There is a bit of design for the new attributes, that's why I did not want to change too much.

**Comment by OpenSuze** [comment]
Here is what is left to do :
- [ ] integrate [the DecomposedFlow rescaler proportional to max AC current load](https://github.com/powsybl/powsybl-entsoe/pull/156)

**Comment by jeandemanged** [comment]
done in https://github.com/powsybl/pypowsybl/pull/845

closing
