### ISSUE TITLE
Allowing to set identifiable properties using update methods

### ISSUE THREAD

**Issue by HugoKulesza** [powsybl/pypowsybl#834]
### Describe the current behavior

If someone currently loads a network with some network elements containing arbitrary additional properties, they are able to see the data in the `get_...` methods associated to the element, but cannot modify the value of the property using the `update_...` methods

### Describe the expected behavior

We should add the possibility to modify the value of a property in all the "update elements" methods

**Comment by jeandemanged** [comment]
proposing to close, available through https://powsybl.readthedocs.io/projects/pypowsybl/en/latest/reference/api/pypowsybl.network.Network.add_elements_properties.html ?
