### ISSUE TITLE
Provide possibility of setting CGMES Export attributes

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/pypowsybl#882]
### Describe the current behavior

The problem is currently that in pypowsybl the java function for setting a generator element as CGMES.ExternalNetworkInjection or EquivalentInjection is not existing this leads to inappropriate CGMES tag while exporting the CGMES for such elements.

### Describe the expected behavior

As in Java it should be possible to set the 
```
  g1.setProperty("CGMES.originalClass", "EquivalentInjection");
  g2.setProperty("CGMES.originalClass", "ExternalNetworkInjection");
```
in order to export the generator to the CGMES tags as mentioned above

### Describe the motivation

Mandatory for a full fledged CGMES Export

**Comment by jeandemanged** [comment]
Hi @AnkurArohi,
This should be possible using [Network.add_elements_properties](https://powsybl.readthedocs.io/projects/pypowsybl/en/latest/reference/api/pypowsybl.network.Network.add_elements_properties.html#pypowsybl.network.Network.add_elements_properties)

**Comment by zamarrenolm** [comment]
As you pointed out, setting properties of network elements is already possible.

This is a minimal code that builds a network with two generators and sets the original CGMES class for them before exporting. The resulting EQ file should have the expected class:

```python
def example_properties():
    n = p.network.create_empty('testpy')
    n.create_substations(id=['S1'])
    n.create_voltage_levels(pd.DataFrame.from_records(
        index='id',
        data=[{'substation_id': 'S1', 'id': 'VL1', 'topology_kind': 'NODE_BREAKER', 'nominal_v': 10}]
    ))
    n.create_generators(pd.DataFrame.from_records(
        index='id',
        data=[
            {'voltage_level_id': 'VL1', 'id': 'G1', 'min_p': 0, 'max_p': 100, 'target_p': 10, 'target_q': 1, 'node': 1, 'voltage_regulator_on': False},
            {'voltage_level_id': 'VL1', 'id': 'G2', 'min_p': 0, 'max_p': 200, 'target_p': 20, 'target_q': 2, 'node': 2, 'voltage_regulator_on': False},
        ]
    ))

    properties = pd.DataFrame({
        'id': ['G1', 'G2'],
        'CGMES.originalClass': ['EquivalentInjection', 'ExternalNetworkInjection'],
    })
    properties.set_index('id', inplace=True)
    n.add_elements_properties(df=properties)

    print(n.get_generators(attributes=['CGMES.originalClass'], id=['G1', 'G2']))
    n.save('/output_folder/testpy-with-properties', 'CGMES')
```

Another way of setting the properties, element by element, would be:

```python
    n.add_elements_properties(id='G1', **{'CGMES.originalClass': 'EquivalentInjection'})
    n.add_elements_properties(id='G2', **{'CGMES.originalClass': 'ExternalNetworkInjection'})
```

You need to use a dictionary to pass the parameters because the key used for the relevant property here has a dot.
