### ISSUE TITLE
per-unit-view apparent power crashes

### ISSUE THREAD

**Issue by nicow-elia** [powsybl/pypowsybl#917]
### Describe the current behavior

```
net = pypowsybl.network.create_ieee14()
net_pu = pypowsybl.per_unit_view(net)
net.nominal_apparent_power # Works
net_pu.sn # Crashes
```

### Describe the expected behavior

`net_pu.sh` should return the same as `net.nominal_apparent_power`

### Environment

pypowsybl 1.8.1

### Relevant Log Output

```

TypeError                                 Traceback (most recent call last)
Cell In[10], line 4
      2 net_pu = pypowsybl.per_unit_view(net)
      3 net.nominal_apparent_power
----> 4 net_pu.sn

File /usr/local/lib/python3.11/site-packages/pypowsybl/network/impl/perunit.py:51, in PerUnitView.sn(self)
     46 @property
     47 def sn(self) -> float:
     48     \"\"\"
     49     The base power, in MW, used for per-uniting
     50     \"\"\"
---> 51     return self._network.nominal_apparent_power()

TypeError: 'int' object is not callable"

```

**Comment by geofjamg** [comment]
Fixed in #923

**Comment by geofjamg** [comment]
@nicow-elia be aware that the per-unit view is deprecated and that the right way to do it now is https://powsybl.readthedocs.io/projects/pypowsybl/en/stable/user_guide/per_unit.html#per-unit-data

**Comment by nicow-elia** [comment]
Oh I like the change! Thanks for pointing me at that! And thanks for making better docs now :)
